---
title: "Country by Country: How COVID-19 case trajectories compare per Capita"
output:
  github_document:
    fig_width: 9
    fig_height: 5
---

```{r}
library(dplyr)
library(magrittr)

load(pins::pin("https://github.com/RamiKrispin/coronavirus/raw/master/data/coronavirus.rda"))

coronavirus <- coronavirus %>%
  mutate(country = `Country.Region`) %>%
  mutate(
    country = case_when(
      country == "United Kingdom" ~ "UK",
      country == "Korea, South" ~ "South Korea",
      TRUE ~ country
    )
  )

coronavirus <- coronavirus %>%
  group_by(country, date, type) %>%
  summarise(cases = sum(cases))
```

```{r}
since_100 <- coronavirus %>%
  group_by(country) %>%
  mutate(total = cumsum(cases)) %>%
  filter(total > 100) %>%
  group_by(country) %>%
  mutate(since_100 = 1:n())
```

```{r}
library(ggplot2)
library(directlabels)

# Validate against current chart https://twitter.com/harryrutter/status/1244253749520084992/photo/1
since_100 %>%
  filter(type == "confirmed") %>%
  ggplot(aes(x = since_100, y = total, color = country)) +
    geom_point(size = 0.5) +
    geom_line(alpha = 0.3) +
    scale_colour_discrete(guide = 'none') +
    scale_x_discrete(expand = c(0, 8)) +
    scale_y_continuous(trans='log2') +
    geom_dl(aes(label = country), method = list(dl.trans(x = x + 0.2), "last.points", cex = 0.8)) +
    ggtitle(label = "Country by Country: How COVID-19 case trajectories compare",
            subtitle = "Cumulative number of confirmed cases, by number of days since 100th case") +
    theme_light()
```

```{r}
population <- read.csv(pins::pin("https://datahub.io/JohnSnowLabs/population-figures-by-country/r/population-figures-by-country-csv.csv"), stringsAsFactors = F)

population <- population %>%
  mutate(
    country = case_when(
      Country == "United States" ~ "US",
      Country == "United Kingdom" ~ "UK",
      Country == "Czech Republic" ~ "Czechia",
      Country == "Iran, Islamic Rep." ~ "Iran",
      Country == "Korea, Rep." ~ "South Korea",
      Country == "Russian Federation" ~ "Russia",
      TRUE ~ Country
    )
  )

countries_missing <- countries[!countries %in% unique(population$country)]
if (length(countries_missing) > 0) stop("Countries missing in population table: ", paste0(countries_missing, collapse = "; "))

population <- transmute(population, country = country, population = Year_2016)
```

```{r}
covid_since_100 <- since_100 %>%
  filter(type == "confirmed") %>%
  left_join(population, by = "country") %>%
  mutate(total_percent = total / population)

highlight_since_100 <- filter(covid_since_100, country %in% c("San Marino", "Andorra", "Iceland", "India", "Luxembourg", "US", "Spain", "Italy", "Japan", "China", "Iran", "UK", "South Korea", "Singapore"))

highlight_since_100 %>%
  ggplot(aes(x = since_100, y = total_percent, colour = country)) +
    geom_line(aes(group = country), data = covid_since_100, alpha = 0.3, colour = "grey") +
    geom_line(alpha = 0.8) +
    scale_colour_discrete(guide = 'none') +
    scale_x_continuous(limits = c(0, 150)) +
    scale_y_continuous(labels = scales::percent, trans='log2') +
    geom_dl(aes(label = country), method = list(dl.trans(x = x + 0.2), "last.points", cex = 0.7)) +
    xlab("Number of days since 100th case") + ylab("") +
    labs(title = "Country by Country per Capita: How COVID-19 case trajectories compare",
         subtitle = "Cumulative number of confirmed cases, divided by population, since 100th case",
         caption = element_text("Source: Johns Hopkins University Center for Systems Science and Engineering. Data Updated: March 28, 2020\nFigure: github.com/javierluraschi/c19chart", color="grey")) +
    theme_bw() + 
    theme(plot.background = element_rect(fill = "#fff1e6"),
          panel.background = element_rect(fill = "#fff1e6",
                                colour = "lightblue",
                                size = 0.5, linetype = "solid"),
          plot.caption = element_text(color="grey60"),
          axis.line.x = element_line(colour = "black"),
          panel.grid.major = element_line(color="grey90"),
          panel.grid.minor = element_line(color="grey90"),
          panel.border = element_blank()) +
    ggsave("covid19-cases-per-capita.png", device = "png", width = 10, height = 5)
```


